(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/kp-button/index"],{"3cef":function(n,e,t){"use strict";function c(n,e,t){return e in n?Object.defineProperty(n,e,{value:t,enumerable:!0,configurable:!0,writable:!0}):n[e]=t,n}Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var o=function(){Promise.all([t.e("common/vendor"),t.e("components/kp-icon/index")]).then(function(){return resolve(t("dd5e"))}.bind(null,t)).catch(t.oe)},a="k-btn",u={name:"KpButton",components:{KpIcon:o},props:{type:{validator:function(n){return["default","primary","dashed","text","info","success","warning","error"].includes(n)},default:"default"},shape:{validator:function(n){return["square","circle","circle-outline"].includes(n)},default:"square"},size:{validator:function(n){return["small","large","default"].includes(n)},default:"default"},disabled:Boolean,icon:{type:String,default:""},iconSize:{type:[Number,String],default:28},long:{type:Boolean,default:!1},plain:{type:Boolean,default:!1}},data:function(){return{prefixCls:a}},computed:{classes:function(){var n;return["".concat(a),"".concat(a,"-").concat(this.type),"".concat(a,"-").concat(this.shape),"".concat(a,"-").concat(this.size),(n={},c(n,"".concat(a,"-long"),this.long),c(n,"".concat(a,"-plain"),this.plain),n)]}},methods:{handleButtonClick:function(n){this.$emit("on-click",n)}},mounted:function(){}};e.default=u},"95d6":function(n,e,t){"use strict";t.r(e);var c=t("a53b"),o=t("ede5");for(var a in o)"default"!==a&&function(n){t.d(e,n,(function(){return o[n]}))}(a);t("27d4");var u,i=t("f0c5"),r=Object(i["a"])(o["default"],c["b"],c["c"],!1,null,"72d19c34",null,!1,c["a"],u);e["default"]=r.exports},a53b:function(n,e,t){"use strict";var c,o=function(){var n=this,e=n.$createElement;n._self._c},a=[];t.d(e,"b",(function(){return o})),t.d(e,"c",(function(){return a})),t.d(e,"a",(function(){return c}))},ede5:function(n,e,t){"use strict";t.r(e);var c=t("3cef"),o=t.n(c);for(var a in c)"default"!==a&&function(n){t.d(e,n,(function(){return c[n]}))}(a);e["default"]=o.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/kp-button/index-create-component',
    {
        'components/kp-button/index-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("95d6"))
        })
    },
    [['components/kp-button/index-create-component']]
]);
