(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/kp-author/index"],{"02a4":function(t,e,n){"use strict";n.r(e);var r=n("5948"),o=n.n(r);for(var i in r)"default"!==i&&function(t){n.d(e,t,(function(){return r[t]}))}(i);e["default"]=o.a},5576:function(t,e,n){"use strict";n.r(e);var r=n("9cdc"),o=n("02a4");for(var i in o)"default"!==i&&function(t){n.d(e,t,(function(){return o[t]}))}(i);n("d326");var c,a=n("f0c5"),u=Object(a["a"])(o["default"],r["b"],r["c"],!1,null,"60c6b851",null,!1,r["a"],c);e["default"]=u.exports},5948:function(t,e,n){"use strict";(function(t){function r(t,e){var n=Object.keys(t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(t);e&&(r=r.filter((function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable}))),n.push.apply(n,r)}return n}function o(t){for(var e=1;e<arguments.length;e++){var n=null!=arguments[e]?arguments[e]:{};e%2?r(Object(n),!0).forEach((function(e){i(t,e,n[e])})):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(n)):r(Object(n)).forEach((function(e){Object.defineProperty(t,e,Object.getOwnPropertyDescriptor(n,e))}))}return t}function i(t,e,n){return e in t?Object.defineProperty(t,e,{value:n,enumerable:!0,configurable:!0,writable:!0}):t[e]=n,t}Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var c=function(){Promise.all([n.e("common/vendor"),n.e("components/kp-icon/index")]).then(function(){return resolve(n("dd5e"))}.bind(null,n)).catch(n.oe)},a=function(){Promise.all([n.e("common/vendor"),n.e("components/kp-avatar/index")]).then(function(){return resolve(n("f3bc"))}.bind(null,n)).catch(n.oe)},u={name:"KpAuthor",components:{KpIcon:c,KpAvatar:a},props:{avatar:String,avatarBg:String,avatarGradient:String,icon:String,iconSize:{type:[String,Number],default:48},title:String,info:String,extra:{type:[Boolean,String,Object],default:!1},shape:{validator:function(t){return["circle","square"].includes(t)},default:"circle"},navigator:String},computed:{extraObj:function(){var t={size:45,icon:"arrow_right",color:"#585860"};switch(this.extra){case"miniprogram":return o({},t,{icon:"miniprogram",color:"#6367ef"});case"wechat":return o({},t,{icon:"wechat",color:"#07C160",size:40});default:break}return this.extra&&this.extra instanceof Object?o({},t,{},this.extra):t}},methods:{handleClick:function(e){if(this.navigator)return t.navigateTo({url:this.navigator});this.$emit("navigate",e)}}};e.default=u}).call(this,n("543d")["default"])},"9cdc":function(t,e,n){"use strict";var r,o=function(){var t=this,e=t.$createElement;t._self._c},i=[];n.d(e,"b",(function(){return o})),n.d(e,"c",(function(){return i})),n.d(e,"a",(function(){return r}))}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/kp-author/index-create-component',
    {
        'components/kp-author/index-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("5576"))
        })
    },
    [['components/kp-author/index-create-component']]
]);
